### ISSUE TITLE
Issue with a negative value 

### ISSUE THREAD

**Issue by LastWillOrNot** [Sispheor/MMM-BMP-sensor#1]
Hello;
I have installed the sensor and your code and I have an unexpected error.

I have only update the default adress in BMP085.py

Sensor seems Ok
`pi@raspberrypi:~ $ i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- 76 --   `

And with a small python script; it seems to work
`pi@raspberrypi:~ $ python bme280.py
Chip ID     : 88
Version     : 1
Temperature :  22.32 C
Pressure :  1009.45091653 hPa
Humidity :  0.0 %
`
But when I launch tour script, I have an error with altitude
`{ Error: ValueError: negative number cannot be raised to a fractional power
    at PythonShell.parseError (/home/pi/MagicMirror/modules/MMM-BMP-sensor/node_modules/python-shell/index.js:184:17)
    at terminateIfNeeded (/home/pi/MagicMirror/modules/MMM-BMP-sensor/node_modules/python-shell/index.js:98:28)
    at ChildProcess.<anonymous> (/home/pi/MagicMirror/modules/MMM-BMP-sensor/node_modules/python-shell/index.js:89:9)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    ----- Python Traceback -----
    File "modules/MMM-BMP-sensor/python_lib/adafruit_python_bpm.py", line 10, in <module>
      "altitude": "{0:0.2f}".format(sensor.read_altitude()),
    File "build/bdist.linux-armv7l/egg/Adafruit_BMP/BMP085.py", line 192, in read_altitude
  traceback: 'Traceback (most recent call last):\n  File "modules/MMM-BMP-sensor/python_lib/adafruit_python_bpm.py", line 10, in <module>\n    "altitude": "{0:0.2f}".format(sensor.read_altitude()),\n  File "build/bdist.linux-armv7l/egg/Adafruit_BMP/BMP085.py", line 192, in read_altitude\nValueError: negative number cannot be raised to a fractional power\n',
  executable: 'python',
  options: null,
  script: 'modules/MMM-BMP-sensor/python_lib/adafruit_python_bpm.py',
  args: null,
  exitCode: 1 }
`

Can you help me ?

Thanks

**Comment by Sispheor** [comment]
I never tried with negative values. 
It's the mm module or the python lib that fail?

**Comment by LastWillOrNot** [comment]
I thinks it's the python lib which fail ...

**Comment by LastWillOrNot** [comment]
I have understood. I don't have the right sensor (bme280 instead of BMP180).
Sorry
