### ISSUE TITLE
Only with the original adafruit sensor?

### ISSUE THREAD

**Issue by GuySwarte** [Sispheor/MMM-BMP-sensor#3]
Hi Nicolas,

Is it right that the module only works with an original Adafruit BMP085 sensor?
My issue: with a BMP180 the module isn't working... If there will be a solution it will be great!

The sensor itself is working. I can read it out with multiple python scripts.

Best regards,
Guy Swarte
the Netherlands.

**Comment by Sispheor** [comment]
No idea about that. Sorry

**Comment by GuySwarte** [comment]
Problem Solved.
